# Stage 1: Build the application
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ---

# Stage 2: Serve the application using Nginx
FROM nginx:stable-alpine

# Copy the static build files from the 'builder' stage
COPY --from=builder /app/dist /usr/share/nginx/html

# The custom nginx.conf is NOT needed for an MPA

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]